# https://rhysd.github.io/actionlint/

name: Testing
on: [push]
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: sudo apt-get install -y libgcrypt20-dev libsndfile1-dev libfftw3-dev libzita-resampler-dev libmpg123-dev ffmpeg
    - name: Test Build
      run: misc/build-cmake.sh
  macos:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v3
    - name: Test Build
      run: misc/macbuild-cmake.sh
